//! Public-surface ports of Python v0.4 `tests/test_template_context_quoting.py`.
//!
//! The Python-only quote-state/value helpers are accounted separately by the completeness gate.
//! Every whole-template contract below keeps its frozen Python name. POSIX contracts that proved
//! safety by running `/bin/sh -c` still run a real shell here; rendering-only substitutes are not
//! accepted for those tests. Windows contracts compile and run only on Windows, where the product
//! actually uses list2cmdline/cmd.exe quoting.

use std::{collections::BTreeMap, path::PathBuf};
use skit_application::delivery::Assembly;
use skit_domain::{Entry, EntryKind, EntryMeta, EntrySettings, Slug};
use skit_runtime::{LaunchError, LaunchPaths, ProgramProbe, build_launch_plan, render_command_template};

fn values(pairs:&[(&str,&str)])->BTreeMap<String,String>{pairs.iter().map(|(n,v)|((*n).to_owned(),(*v).to_owned())).collect()}
#[derive(Debug,Default)]struct FakeProbe{programs:BTreeMap<String,PathBuf>,dirs:Vec<PathBuf>}
impl ProgramProbe for FakeProbe{fn find_program(&self,n:&str)->Option<PathBuf>{self.programs.get(n).cloned()}fn is_file(&self,_:&std::path::Path)->bool{false}fn is_dir(&self,p:&std::path::Path)->bool{self.dirs.iter().any(|x|x==p)}fn is_executable(&self,_:&std::path::Path)->bool{false}}
fn command_entry(t:&str,p:&[&str])->Entry{let mut m=EntryMeta::minimal("Demo",EntryKind::parse("command").unwrap());m.workdir="invoke".into();EntrySettings{template:t.into(),params:p.iter().map(|x|(*x).into()).collect(),..EntrySettings::default()}.write_to_meta(&mut m);Entry{slug:Slug::parse("demo").unwrap(),meta:m}}
fn launch_command(t:&str,p:&[&str],cv:BTreeMap<String,String>,extra:&[&str])->skit_runtime::LaunchPlan{let e=command_entry(t,p);let a=Assembly{args:extra.iter().map(|x|(*x).into()).collect(),masked_args:extra.iter().map(|x|(*x).into()).collect(),command_values:cv.clone(),masked_command_values:cv,..Assembly::default()};let mut programs=BTreeMap::new();#[cfg(windows)]programs.insert("cmd.exe".into(),PathBuf::from("cmd.exe"));#[cfg(not(windows))]programs.insert("sh".into(),PathBuf::from("/bin/sh"));build_launch_plan(&e,&LaunchPaths{script:PathBuf::from("unused"),entry_dir:PathBuf::from("/data/scripts/demo"),invoke_cwd:PathBuf::from("/invoke")},&a,None,None,&FakeProbe{programs,dirs:vec![PathBuf::from("/invoke")]}).unwrap()}
#[cfg(not(windows))]fn run_sh(c:&str)->std::process::Output{std::process::Command::new("/bin/sh").args(["-c",c]).output().unwrap()}
#[cfg(not(windows))]fn assert_sh_stdout(c:&str,e:&str){let o=run_sh(c);assert!(o.status.success(),"shell failed: {}",String::from_utf8_lossy(&o.stderr));assert_eq!(String::from_utf8(o.stdout).unwrap(),e);}

#[cfg(not(windows))]#[test]fn test_double_quoted_placeholder_neutralizes_command_substitution(){let c=render_command_template("printf \"%s\\n\" \"{value}\"",&values(&[("value","$(printf unexpected)")])).unwrap();assert_eq!(c,"printf \"%s\\n\" \"\\$(printf unexpected)\"");assert_sh_stdout(&c,"$(printf unexpected)\n");}
#[cfg(not(windows))]#[test]fn test_single_quoted_placeholder_stays_literal_with_apostrophe_and_substitution(){let c=render_command_template("echo '{v}'",&values(&[("v","a'b $(id)")])).unwrap();assert_eq!(c,"echo 'a'\\''b $(id)'");assert_sh_stdout(&c,"a'b $(id)\n");}
#[cfg(not(windows))]#[test]fn test_unquoted_placeholder_embedded_in_a_word(){let c=render_command_template("echo scale={width}:-1",&values(&[("width","640")])).unwrap();assert_eq!(c,"echo scale=640:-1");assert_sh_stdout(&c,"scale=640:-1\n");}
#[cfg(not(windows))]#[test]fn test_unquoted_placeholder_hostile_value_cannot_escape_the_word(){let c=render_command_template("echo scale={width}:-1",&values(&[("width","640 $(id)")])).unwrap();assert_eq!(c,"echo scale='640 $(id)':-1");assert_sh_stdout(&c,"scale=640 $(id):-1\n");}
#[cfg(not(windows))]#[test]fn test_unfilled_placeholder_travels_through_unchanged(){assert_eq!(render_command_template("echo {leftover}",&BTreeMap::new()).unwrap(),"echo {leftover}");}
#[cfg(not(windows))]#[test]fn test_brace_escapes_collapse_inside_quotes_without_disturbing_state(){let c=render_command_template("echo \"{{x}} {v}\"",&values(&[("v","$X")])).unwrap();assert_eq!(c,"echo \"{x} \\$X\"");assert_sh_stdout(&c,"{x} $X\n");}
#[cfg(not(windows))]#[test]fn test_substituted_value_containing_double_braces_is_not_rescanned(){let c=render_command_template("echo \"{v}\"",&values(&[("v","{{x}}")])).unwrap();assert_eq!(c,"echo \"{{x}}\"");assert_sh_stdout(&c,"{{x}}\n");}
#[cfg(not(windows))]#[test]fn test_extra_args_are_appended_shell_quoted_after_the_template(){let p=launch_command("echo {v}",&["v"],values(&[("v","hi")]),&["a b","$X"]);assert_eq!(p.program,PathBuf::from("/bin/sh"));assert_eq!(p.args,["-c","echo hi 'a b' '$X'"]);assert_sh_stdout(&p.args[1],"hi a b $X\n");}
#[cfg(not(windows))]#[test]fn test_quote_state_affects_only_later_placeholders(){let c=render_command_template("echo \"{a}\" {b}",&values(&[("a","$A"),("b","$B")])).unwrap();assert_eq!(c,"echo \"\\$A\" '$B'");assert_sh_stdout(&c,"$A $B\n");}
#[cfg(not(windows))]#[test]fn test_describe_command_uses_the_same_context_aware_quoting(){let p=launch_command("echo \"{v}\"",&["v"],values(&[("v","$(id)")]),&[]);assert_eq!(p.args,["-c","echo \"\\$(id)\""]);assert_eq!(p.display,"echo \"\\$(id)\"");}
#[cfg(not(windows))]#[test]fn test_dangling_backslash_before_a_placeholder_cannot_eat_the_value_escape(){let c=render_command_template("printf \"%s\\n\" \"foo\\{name}\"",&values(&[("name","$(printf pwned)")])).unwrap();assert_eq!(c,"printf \"%s\\n\" \"foo\\\\\\$(printf pwned)\"");assert_sh_stdout(&c,"foo\\$(printf pwned)\n");}
#[cfg(not(windows))]#[test]fn test_dangling_backslash_in_unquoted_position_is_neutralized_too(){let c=render_command_template("printf %s\\\\n foo\\{name}",&values(&[("name","$(printf pwned)")])).unwrap();assert_eq!(c,"printf %s\\\\n foo\\\\'$(printf pwned)'");assert_sh_stdout(&c,"foo\\$(printf pwned)\n");}
#[cfg(not(windows))]#[test]fn test_even_backslash_run_before_a_placeholder_adds_no_neutralizer(){let c=render_command_template("printf \"%s\\n\" \"a\\\\{name}\"",&values(&[("name","$(printf pwned)")])).unwrap();assert_eq!(c,"printf \"%s\\n\" \"a\\\\\\$(printf pwned)\"");assert_sh_stdout(&c,"a\\$(printf pwned)\n");}
#[cfg(not(windows))]#[test]fn test_dangling_backslash_before_brace_escape_and_unfilled_placeholder_is_absorbed(){let c=render_command_template("printf \"%s\\n\" \"\\{{x}} {later}\"",&values(&[("later","$(printf pwned)")])).unwrap();assert_eq!(c,"printf \"%s\\n\" \"\\{x} \\$(printf pwned)\"");assert_sh_stdout(&c,"\\{x} $(printf pwned)\n");assert_eq!(render_command_template("\"\\{never} {later}\"",&values(&[("later","$(x)")])).unwrap(),"\"\\{never} \\$(x)\"");}
#[cfg(windows)]#[test]fn test_render_win32_uses_list2cmdline_not_posix_quoting(){let p=launch_command("echo {v}",&["v"],values(&[("v","a b")]),&["c d"]);assert_eq!(p.program,PathBuf::from("cmd.exe"));assert_eq!(p.args,["/C","echo \"a b\" \"c d\""]);}
#[cfg(windows)]#[test]fn test_render_win32_repl_handles_brace_escapes_and_unfilled_placeholders(){assert_eq!(render_command_template("echo {{x}} {filled} {unfilled}",&values(&[("filled","v")])).unwrap(),"echo {x} v {unfilled}");}
#[cfg(not(windows))]#[test]fn test_value_survives_a_nested_command_substitution_verbatim(){for(t,v)in[("printf \"%s\\n\" \"$(printf %s {v})\"","safe; printf INJECTED"),("printf \"%s\\n\" \"$(printf %s {v})\"","a b"),("printf \"%s\\n\" \"$(printf %s \"{v}\")\"","$(printf PWNED)"),("printf \"%s\\n\" \"$(printf %s \"{v}\")\"","a b"),("printf \"%s\\n\" \"`printf %s {v}`\"","safe; printf INJECTED"),("printf \"%s\\n\" \"`printf %s '{v}'`\"","it's $HOME"),("printf \"%s\\n\" \"$(printf %s \"$(printf %s \"{v}\")\")\"","deep 'a b' $X")]{let c=render_command_template(t,&values(&[("v",v)])).unwrap();assert_sh_stdout(&c,&format!("{v}\n"));}}
#[cfg(not(windows))]#[test]fn test_double_quotes_nested_in_backticks_are_refused_not_guessed(){let e=render_command_template("printf \"%s\\n\" \"`printf %s \"{v}\"`\"",&values(&[("v","$(printf PWNED)")])).unwrap_err();assert!(matches!(&e,LaunchError::UnsafeTemplatePlaceholder{..}));assert_eq!(e.to_string(),"Can't safely fill in a value inside double quotes nested in a `…` command substitution — the shell strips one layer of escaping there. Rewrite that part of the template with $(…) instead of backticks.");}
#[test]fn rust_additive_uppercase_placeholder_is_substituted(){assert_eq!(render_command_template("echo {NAME}",&values(&[("NAME","x")])).unwrap(),"echo x");}
#[cfg(not(windows))]#[test]fn rust_additive_replacement_text_is_not_reparsed_as_another_placeholder(){assert_eq!(render_command_template("echo {a} {b}",&values(&[("a","{b}"),("b","real")])).unwrap(),"echo '{b}' real");}
#[cfg(not(windows))]#[test]fn rust_additive_double_quoted_value_escapes_backslash_quote_dollar_and_backtick(){assert_eq!(render_command_template("printf \"%s\" \"{v}\"",&values(&[("v","\\\"$x`y`")])).unwrap(),"printf \"%s\" \"\\\\\\\"\\$x\\`y\\`\"");}
