[package]
name = "skit-runtime"
description = "Process and runtime adapters for skit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
shlex.workspace = true
thiserror.workspace = true
skit-application.workspace = true
skit-domain.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
