[package]
name = "skit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "skit"
path = "src/main.rs"

[dependencies]
clap.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
skit-core = { path = "../skit-core" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
