//! Exact completeness accounting for Python v0.4 `tests/test_config.py` at `main@206f9ef`.
use std::collections::BTreeSet;
use syn::{Attribute,Item};

const EXECUTABLE:&[&str]=&[
"test_defaults_when_no_config","test_full_mirror_saves_all_four_vectors","test_axes_are_independent","test_github_release_urls_expand_from_one_base","test_axis_choice_readers_are_blind_to_the_master_switch","test_update_mirror_axes_fresh_url_auto_enables","test_update_mirror_axes_off_on_empty_stays_off","test_update_mirror_axes_enabled_stays_on_while_a_url_remains","test_update_mirror_axes_clearing_the_last_url_disables","test_update_mirror_axes_paused_stays_paused_and_preserves_others","test_update_mirror_axes_none_leaves_axes_untouched","test_enable_works_for_each_single_axis","test_enable_restores_saved_urls","test_enable_refuses_when_nothing_saved","test_save_mirror_preserves_other_keys","test_mirror_env_overlays_all_vectors","test_mirror_env_defers_to_user_index","test_mirror_env_defers_to_user_python_mirror","test_mirror_env_does_not_defer_on_extra_index_url","test_mirror_env_does_not_defer_on_uv_index","test_mirror_env_injects_when_index_env_blank","test_mirror_env_injects_when_python_mirror_blank","test_mirror_env_skips_empty_urls","test_load_mirror_ignores_malformed_section","test_load_mirror_rejects_string_enabled","test_load_mirror_ignores_non_str_url","test_load_mirror_blanks_non_https_uv_binary","test_load_mirror_preserves_https_uv_binary","test_nju_preset_uv_binary_stays_https","test_save_editor_backs_up_corrupt_config_instead_of_wiping_it","test_save_mirror_backs_up_corrupt_config_instead_of_wiping_it","test_save_editor_still_preserves_other_keys_when_config_is_valid","test_looks_blocked_true_when_unreachable","test_looks_blocked_false_when_reachable","test_looks_blocked_short_circuits_on_first_host","test_looks_blocked_true_when_second_host_unreachable","test_bash_path_defaults_to_empty","test_bash_path_round_trip","test_bash_path_strips_and_clears","test_bash_path_garbage_normalizes_to_empty","test_bash_path_garbage_section_normalizes_to_empty","test_bash_path_save_preserves_other_keys","test_bash_path_clear_preserves_other_shell_keys","test_js_runner_defaults_to_empty","test_js_runner_round_trip","test_js_runner_unknown_value_normalizes_to_empty","test_js_runner_garbage_section_normalizes_to_empty","test_js_runner_clears_and_drops_section","test_js_runner_save_preserves_other_keys"];
const CLOSED:&[&str]=&[
"test_compose_enables_iff_any_axis_on","test_is_url_token_accepts_pastable_http_urls","test_is_url_token_rejects_non_urls","test_axis_choice_readers","test_github_base_recovers_a_custom_derivable_base","test_axis_display_helpers_exact","test_axes_summary_exact_strings","test_mirrors_line_three_states_exact","test_disable_keeps_urls_but_turns_off","test_load_config_tolerates_corrupt_toml","test_save_editor_backup_failure_still_warns_and_does_not_claim_backup"];
fn is_test(a:&[Attribute])->bool{a.iter().any(|x|x.path().is_ident("test"))}
fn names(s:&str)->BTreeSet<String>{syn::parse_file(s).unwrap().items.into_iter().filter_map(|i|match i{Item::Fn(f)if is_test(&f.attrs)&&f.sig.ident.to_string().starts_with("test_")=>Some(f.sig.ident.to_string()),_=>None}).collect()}
#[test]
fn test_config_frozen_names_are_exactly_accounted(){
 assert_eq!(EXECUTABLE.len(),49);assert_eq!(CLOSED.len(),11);
 let expected=EXECUTABLE.iter().copied().collect::<BTreeSet<_>>();let closed=CLOSED.iter().copied().collect::<BTreeSet<_>>();assert_eq!(expected.len(),49);assert_eq!(closed.len(),11);assert!(expected.is_disjoint(&closed));assert_eq!(expected.len()+closed.len(),60);
 let mut actual=BTreeSet::new();for source in[
 include_str!("../../skit-store/tests/port_test_config_full_mirror.rs"),include_str!("../../skit-store/tests/port_test_config_axes_exact.rs"),include_str!("../../skit-store/tests/port_test_config_mirror_state.rs"),include_str!("../../skit-store/tests/port_test_config_mirror_enable.rs"),include_str!("../../skit-store/tests/port_test_config_mirror_env.rs"),include_str!("../../skit-store/tests/port_test_config_mirror_shapes.rs"),include_str!("../../skit-store/tests/port_test_config_uv_binary.rs"),include_str!("../../skit-store/tests/port_test_config_recovery.rs"),include_str!("port_test_config_recovery_cli.rs"),include_str!("../../skit-store/tests/port_test_config_persistence.rs"),include_str!("../../skit-store/tests/port_test_config_runtime_choices.rs"),include_str!("../../skit-runtime/tests/port_test_config_network.rs")]{actual.extend(names(source));}
 let actual=actual.iter().map(String::as_str).collect::<BTreeSet<_>>();assert_eq!(actual,expected,"config executable parity is missing, extra, or mislabeled");assert!(actual.is_disjoint(&closed));
}
