[package]
name = "skit-language"
description = "Source analysis and rewrite support for skit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
skit-i18n.workspace = true
pep440_rs.workspace = true
pep508_rs.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-bash.workspace = true
tree-sitter-fish.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-powershell.workspace = true
tree-sitter-python.workspace = true
tree-sitter-typescript.workspace = true
skit-domain.workspace = true

[dev-dependencies]
skit-i18n.workspace = true
tempfile.workspace = true

[lints]
workspace = true
