[package]
name = "skit-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
atomic-write-file.workspace = true
pep440_rs.workspace = true
pep508_rs.workspace = true
serde.workspace = true
toml.workspace = true
tree-sitter.workspace = true
tree-sitter-python.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
