//! Frozen mirror-environment contracts from Python v0.4 `tests/test_config.py`.
use std::collections::BTreeMap;
use skit_store::FileConfigStore;
use tempfile::TempDir;
const PYPI:&str="https://pypi.tuna.tsinghua.edu.cn/simple";const PYTHON:&str="https://mirror.nju.edu.cn/github-release/astral-sh/python-build-standalone/";const UV:&str="https://mirror.nju.edu.cn/github-release/astral-sh/uv";const NPM:&str="https://registry.npmmirror.com";
fn full()->(TempDir,FileConfigStore){let r=TempDir::new().unwrap();let s=FileConfigStore::new(r.path());s.set_many(&BTreeMap::from([("mirror.pypi".into(),"tsinghua".into()),("mirror.github".into(),"nju".into()),("mirror.npm".into(),"npmmirror".into())])).unwrap();(r,s)}
#[test]fn test_mirror_env_overlays_all_vectors(){let(_r,s)=full();let e=s.mirror_environment(&BTreeMap::new()).unwrap();assert_eq!(e.get("UV_DEFAULT_INDEX").map(String::as_str),Some(PYPI));assert_eq!(e.get("UV_PYTHON_INSTALL_MIRROR").map(String::as_str),Some(PYTHON));assert_eq!(e.get("NPM_CONFIG_REGISTRY").map(String::as_str),Some(NPM));assert_eq!(s.mirror().unwrap().uv_binary,UV);}
#[test]fn test_mirror_env_defers_to_user_index(){for k in["UV_DEFAULT_INDEX","UV_INDEX_URL"]{let(_r,s)=full();let e=s.mirror_environment(&BTreeMap::from([(k.to_owned(),"https://mine/simple".into())])).unwrap();assert!(!e.contains_key("UV_DEFAULT_INDEX"),"{k}");assert!(e.contains_key("UV_PYTHON_INSTALL_MIRROR"),"{k}");}}
#[test]fn rust_additive_mirror_env_defers_to_uv_default_index(){let(_r,s)=full();assert!(!s.mirror_environment(&BTreeMap::from([("UV_DEFAULT_INDEX".into(),"x".into())])).unwrap().contains_key("UV_DEFAULT_INDEX"));}
#[test]fn rust_additive_mirror_env_defers_to_uv_index_url(){let(_r,s)=full();assert!(!s.mirror_environment(&BTreeMap::from([("UV_INDEX_URL".into(),"x".into())])).unwrap().contains_key("UV_DEFAULT_INDEX"));}
#[test]fn test_mirror_env_defers_to_user_python_mirror(){let(_r,s)=full();let e=s.mirror_environment(&BTreeMap::from([("UV_PYTHON_INSTALL_MIRROR".into(),"https://mine/py/".into())])).unwrap();assert!(!e.contains_key("UV_PYTHON_INSTALL_MIRROR"));assert!(e.contains_key("UV_DEFAULT_INDEX"));}
#[test]fn test_mirror_env_does_not_defer_on_extra_index_url(){let(_r,s)=full();assert_eq!(s.mirror_environment(&BTreeMap::from([("UV_EXTRA_INDEX_URL".into(),"https://x".into())])).unwrap().get("UV_DEFAULT_INDEX").map(String::as_str),Some(PYPI));}
#[test]fn test_mirror_env_does_not_defer_on_uv_index(){let(_r,s)=full();assert_eq!(s.mirror_environment(&BTreeMap::from([("UV_INDEX".into(),"https://x".into())])).unwrap().get("UV_DEFAULT_INDEX").map(String::as_str),Some(PYPI));}
#[test]fn test_mirror_env_injects_when_index_env_blank(){let(_r,s)=full();assert_eq!(s.mirror_environment(&BTreeMap::from([("UV_INDEX_URL".into(),String::new())])).unwrap().get("UV_DEFAULT_INDEX").map(String::as_str),Some(PYPI));}
#[test]fn test_mirror_env_injects_when_python_mirror_blank(){let(_r,s)=full();assert_eq!(s.mirror_environment(&BTreeMap::from([("UV_PYTHON_INSTALL_MIRROR".into(),String::new())])).unwrap().get("UV_PYTHON_INSTALL_MIRROR").map(String::as_str),Some(PYTHON));}
#[test]fn rust_additive_disable_keeps_saved_urls_and_env_overlay_off(){let(_r,s)=full();s.set("mirror","off").unwrap();let m=s.mirror().unwrap();assert!(!m.enabled);assert_eq!(m.pypi,PYPI);assert_eq!(m.uv_binary,UV);assert!(s.mirror_environment(&BTreeMap::new()).unwrap().is_empty());}
